### ISSUE TITLE
老大，有没有交流群？

### ISSUE THREAD

**Issue by monsoon585** [ngfchl/NewPtools#5]
老大，有没有交流群？
http://ptools.fun/doc/11/这里的付费二维码失效，扫小客服二维码也不通过

**Comment by ngfchl** [comment]
> 老大，有没有交流群？ [http://ptools.fun/doc/11 / 这里的付费二维码失效，扫小客服二维码也不通过](http://ptools.fun/doc/11/%E8%BF%99%E9%87%8C%E7%9A%84%E4%BB%98%E8%B4%B9%E4%BA%8C%E7%BB%B4%E7%A0%81%E5%A4%B1%E6%95%88%EF%BC%8C%E6%89%AB%E5%B0%8F%E5%AE%A2%E6%9C%8D%E4%BA%8C%E7%BB%B4%E7%A0%81%E4%B9%9F%E4%B8%8D%E9%80%9A%E8%BF%87)

二维码反馈没那么及时，毕竟业余搞，TG 也可以
https://t.me/ptools_chat
