### ISSUE TITLE
时间ptt无法获取上传下载量

### ISSUE THREAD

**Issue by fengs2021** [ngfchl/NewPtools#6]
时间ptt无法获取上传下载量

**Comment by fengs2021** [comment]
uploaded = models.BigIntegerField(verbose_name='上传量', default=0)
    downloaded = models.BigIntegerField(verbose_name='下载量', default=0)

代码中识别的是上传量，但是ptt是上传，所以识别不到，求修复

**Comment by ngfchl** [comment]
> ```
> uploaded = models.BigIntegerField(verbose_name='上传量', default=0)
> downloaded = models.BigIntegerField(verbose_name='下载量', default=0)
> ```
> 
> 代码中识别的是上传量，但是 ptt 是上传，所以识别不到，求修复

已修复
